tmux:
    symbols:
        branch: ' ⎇  '
        hashprefix: ':'
        ahead: ↑·
        behind: ↓·
        staged: ' '
        conflict: '✗ '
        modified: ' '
        untracked: ' '
        stashed: '⚑ '
        clean: ✔
    styles:
        clear: '#[fg=default]'
        state: '#[fg=red]'
        branch: '#[fg=white,bold]'
        remote: '#[fg=cyan]'
        staged: '#[fg=colour150]'
        conflict: '#[fg=red]'
        modified: '#[fg=colour216]'
        untracked: '#[fg=magenta]'
        stashed: '#[fg=cyan]'
        clean: '#[fg=colour77]'
        divergence: '#[fg=default]'
    _layout: [branch, ' ', flags , .. , divergence]
    layout: [divergence, ' ', branch, ' ', flags]
    options:
        branch_max_len: 50
        branch_trim: center
        ellipsis: '...'
