############# OPTIONS ############
set -g mouse on
set -g base-index 1
set -sg escape-time 0
set -g status-interval 1
set -g renumber-windows on
set -g history-limit 1000
set -g default-terminal "tmux-256color"
setw -g mode-keys vi
set-option -g focus-events on
set-option -g allow-rename off
set-option -g xterm-keys on
set-option -g detach-on-destroy off
set-option -sa terminal-overrides ",xterm*:Tc"
##################################

############# HOTKEYS ############
# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# splits
unbind |
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# windows actions
bind -n M-Enter new-window
bind -n M-F11 prev
bind -n M-F12 next
bind -n M-F8 kill-window
bind -n C-F11 swap-window -t -1\; select-window -t -1
bind -n C-F12 swap-window -t +1\; select-window -t +1
bind -n M-k next
bind -n M-j prev

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

# pains actions
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-d kill-pane

# session manager
bind Enter run-shell "~/.scripts/tmux/session_manager.sh --window-popup"
bind r run-shell "~/.scripts/tmux/session_manager.sh --window-rename"
bind a run-shell "~/.scripts/tmux/session_manager.sh --session-new"
bind -n M-Space run-shell "~/.scripts/tmux/session_manager.sh"
##################################

############## THEME ############# gruvbox dark (medium)
set-option -g status "on"

# default statusbar color
#set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1
set-option -g status-style bg='#272e33',fg='#b2a993' # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=colour241 #fg2
set-option -g pane-border-style fg=colour238 #bg1

# message infos
set-option -g message-style bg=#272e33,fg=#b2a993 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg
##################################

############ STATUSBAR ###########
set-option -g status-justify "absolute-centre"
set-option -g status-left-length 80
set-option -g status-right-length 80
set-option -g status-left-style none
set-option -g status-right-style none
set-option -g status-position "top"
set-window-option -g window-status-separator ""

set-option -g status-left "#[bg=#a7c080, fg=#272e33,bold]  #S "
set-option -g status-right "#(~/.scripts/tmux/git_status.sh #{pane_current_path}) "
set-window-option -g window-status-format "#[bg=#272e33,fg=#b2a993]  #I: #W  "
set-window-option -g window-status-current-format "#[bg=#a7c080, fg=#272e33,bold] #{?window_zoomed_flag,•, }#I: #W  "
##################################

############# PLUGINS ############
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'
##################################
