# Theme
globinclude themes/everforest_medium.conf

# Font
font_family             FiraCode Nerd Font
font_size               12
modify_font             cell_height -1px

# Window
remember_window_size    no
initial_window_width    1200
initial_window_height   290
confirm_os_window_close 0
placement_strategy      top-left

# Other
cursor_shape            underline
cursor_blink_interval   0.5
enable_audio_bell no
