#
# Font settings
#
font_family         FiraCode Nerd Font
font_size           12
modify_font         cell_height -1px


#
# Cursor settings
#
cursor_shape            underline
cursor_blink_interval   0.5


#
# Window settings
#
remember_window_size    no
initial_window_width    1200
initial_window_height   290
confirm_os_window_close 0
placement_strategy      top-left


#
# Colors settings [EVERFOREST medium]
#
# core
background  #2d353b
foreground  #d3c6aa

# black
color0      #475258
color8      #475258

# red
color1      #e67e80
color9      #e67e80

# green
color2      #a7c080
color10     #a7c080

# yellow
color3      #dbbc7f
color11     #dbbc7f

# blue
color4      #7fbbb3
color12     #7fbbb3

# magenta
color5      #d699b6
color13     #d699b6

# cyan
color6      #83c092
color14     #83c092

# white
color7      #d3c6aa
color15     #d3c6aa
